# Do a snapshot deployment from the develop branch
name: Deploy Snapshot

# Run job on push to develop
on:
    push:
        branches:
            - 'develop'

jobs:
    snapshot:
        runs-on: ubuntu-18.04
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - name: Install Java and Maven
              uses: actions/setup-java@v1
              with:
                  java-version: 8

            - name: Install xmlstarlet
              run: |
                  sudo apt-get update -y
                  sudo apt-get install -y xmlstarlet

            - name: Prepare snapshot release
              run: |
                  cp pom.xml pom_tmp.xml
                  xmlstarlet ed -N pom="http://maven.apache.org/POM/4.0.0" -u '/pom:project/pom:version' \
                      -v "$(xmlstarlet sel -N pom="http://maven.apache.org/POM/4.0.0" -t \
                      -m '/pom:project/pom:version' -v . -n pom_tmp.xml)-SNAPSHOT" pom_tmp.xml > pom.xml
                  rm -f pom_tmp.xml
                  export GPG_TTY=$(tty)

            - name: Release Maven package
              uses: samuelmeuli/action-maven-publish@v1
              with:
                  gpg_private_key: ${{ secrets.gpg_private_key }}
                  gpg_passphrase: ${{ secrets.gpg_passphrase }}
                  nexus_username: ${{ secrets.nexus_username }}
                  nexus_password: ${{ secrets.nexus_password }}

            - name: Upload build artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: gcaptchavalidator
                  path: target

            - name: Upload coverage report
              uses: actions/upload-artifact@v2
              with:
                  name: code-coverage-report
                  path: target/site/jacoco
