name: Rebase master

on:
    push:
        branches: [ master ]

jobs:
    rebase:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ github.token }}
                  ref: 'develop'
            - name: Rebase
              run: |
                  git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
                  git config --global user.email "p.zarrad@outlook.de"
                  git config --global user.name "Pascal Zarrad"
                  git rebase remotes/origin/master
                  git push --force
